"""Finite-population JAX agent-based simulation."""

from .complete_graph import CompleteGraph, complete_graph, validate_complete_graph
from .sampling import (
    InitializedABM,
    InitializationMetadata,
    initialize_continuous_paper,
    initialize_continuous_paper_batch,
    initialize_grid_matched,
    initialize_grid_matched_batch,
    sample_continuous_paper_q,
    sample_edge_states,
    sample_grid_matched_q,
)
from .statistics import (
    BinnedMomentEstimates,
    BinnedSufficientStatistics,
    QBinSpec,
    aggregate_variance_records,
    derive_variance_moments,
)
from .simulation import (
    ABMState,
    DeterministicStepRecord,
    InstrumentedStepRecord,
    SimulationResult,
    StepRecord,
    action_probabilities,
    sample_actions,
    simulate,
    simulate_batch,
    simulate_batch_jit,
    simulate_debug,
    simulate_instrumented,
    simulate_instrumented_batch,
    simulate_instrumented_batch_jit,
    simulate_instrumented_jit,
    simulate_jit,
    step_given_actions,
    stochastic_step,
    stochastic_step_instrumented,
)

__all__ = [
    "ABMState",
    "BinnedMomentEstimates",
    "BinnedSufficientStatistics",
    "CompleteGraph",
    "DeterministicStepRecord",
    "InitializedABM",
    "InitializationMetadata",
    "InstrumentedStepRecord",
    "QBinSpec",
    "SimulationResult",
    "StepRecord",
    "action_probabilities",
    "aggregate_variance_records",
    "complete_graph",
    "derive_variance_moments",
    "initialize_continuous_paper",
    "initialize_continuous_paper_batch",
    "initialize_grid_matched",
    "initialize_grid_matched_batch",
    "sample_actions",
    "sample_continuous_paper_q",
    "sample_edge_states",
    "sample_grid_matched_q",
    "simulate",
    "simulate_batch",
    "simulate_batch_jit",
    "simulate_debug",
    "simulate_instrumented",
    "simulate_instrumented_batch",
    "simulate_instrumented_batch_jit",
    "simulate_instrumented_jit",
    "simulate_jit",
    "step_given_actions",
    "stochastic_step",
    "stochastic_step_instrumented",
    "validate_complete_graph",
]
