"""Finite-population JAX agent-based simulation."""

from .complete_graph import CompleteGraph, complete_graph, validate_complete_graph
from .sampling import (
    InitializedABM,
    InitializationMetadata,
    initialize_continuous_paper,
    initialize_continuous_paper_batch,
    initialize_grid_matched,
    initialize_grid_matched_batch,
    sample_continuous_paper_q,
    sample_edge_states,
    sample_grid_matched_q,
)
from .simulation import (
    ABMState,
    DeterministicStepRecord,
    SimulationResult,
    StepRecord,
    action_probabilities,
    sample_actions,
    simulate,
    simulate_batch,
    simulate_batch_jit,
    simulate_debug,
    simulate_jit,
    step_given_actions,
    stochastic_step,
)

__all__ = [
    "ABMState",
    "CompleteGraph",
    "DeterministicStepRecord",
    "InitializedABM",
    "InitializationMetadata",
    "SimulationResult",
    "StepRecord",
    "action_probabilities",
    "complete_graph",
    "initialize_continuous_paper",
    "initialize_continuous_paper_batch",
    "initialize_grid_matched",
    "initialize_grid_matched_batch",
    "sample_actions",
    "sample_continuous_paper_q",
    "sample_edge_states",
    "sample_grid_matched_q",
    "simulate",
    "simulate_batch",
    "simulate_batch_jit",
    "simulate_debug",
    "simulate_jit",
    "step_given_actions",
    "stochastic_step",
    "validate_complete_graph",
]
